### ISSUE TITLE
Console - Create application to reset barcode registration.

### ISSUE THREAD

**Issue by pjamenaja** [pjamenaja/magnum-web#57]

**Comment by Abystar** [comment]
Usage:

dotnet run -p MagnumConsole BarcodeReset \
--h=${MAGNUM_FIREBASE_URL} \
--user=${MAGNUM_DB_USERNAME} \
--password=${MAGNUM_DB_PASSWORD} \
--serial=3069567966 \
--pin=8656042058 \
--key=${MAGNUM_FIREBASE_KEY}
