### ISSUE TITLE
Web - Add metric table to show web stat on page.

### ISSUE THREAD

**Issue by pjamenaja** [pjamenaja/magnum-web#67]

**Comment by Abystar** [comment]
1000 Page Views = ยอดวิว
1000 Order Shipped = จำนวน barcode?
1000 Days Uptime = วันเปิด

**Comment by pjamenaja** [comment]
ตามนั้น

**Comment by Abystar** [comment]
![image](https://user-images.githubusercontent.com/1989674/65817226-f0553600-e22e-11e9-8f3f-a6bd2137b498.png)
![image](https://user-images.githubusercontent.com/1989674/65817236-0662f680-e22f-11e9-9a97-09ba3efefd59.png)
