### ISSUE TITLE
Migrate the existing barcodes to the new structure.

### ISSUE THREAD

**Issue by Abystar** [pjamenaja/magnum-web#76]
bcPath = string.Format("barcodes/{0}/{1}/{2}/{3}/{4}/{5}/{6}/{7}"
                    , dat.SerialNumber.ToCharArray()[0]
                    , dat.SerialNumber.ToCharArray()[1]
                    , dat.SerialNumber.ToCharArray()[2]
                    , dat.Pin.ToCharArray()[0]
                    , dat.Pin.ToCharArray()[1]
                    , dat.Pin.ToCharArray()[2]
                    , dat.SerialNumber
                    , dat.Pin);

**Comment by pjamenaja** [comment]
[BarcodeMigrate.zip](https://github.com/pjamenaja/magnum-web/files/3628844/BarcodeMigrate.zip)

Old barcodes to migrate attached.
