### ISSUE TITLE
Web - Will MAGNUM_EMAIL_TO support multiple emails separated by comma?

### ISSUE THREAD

**Issue by pjamenaja** [pjamenaja/magnum-web#90]

**Comment by Abystar** [comment]
![image](https://user-images.githubusercontent.com/1989674/65834593-ab9cce00-e306-11e9-8895-33b7608c8164.png)
![image](https://user-images.githubusercontent.com/1989674/65834607-c96a3300-e306-11e9-88ce-ea06f2e05fa8.png)

Support multiple email address with comma ,
